### ISSUE TITLE
Hanging SendFile Tests

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/HttpSysServer#270]
The tests `ResponseSendFileExceptions_ClientDisconnectsBeforeSecondSend_SendThrows` and `ResponseSendFile_ClientDisconnectsBeforeSecondSend_SendCompletesSilently` are failing consistently on Win7 and Win2008R2 on desktop CLR.

The tests hang on the first `SendFileAsync` calls, specifically at https://github.com/aspnet/WebListener/blob/dev/test/Microsoft.Net.Http.Server.FunctionalTests/ResponseSendFileTests.cs#L521 and https://github.com/aspnet/WebListener/blob/dev/test/Microsoft.Net.Http.Server.FunctionalTests/ResponseSendFileTests.cs#L554.

**Comment by muratg** [comment]
@Tratcher please feel free to move to 1.2.0 if investigation takes too long.
