### ISSUE TITLE
WebListener vs HttpListener

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#271]
Several folks have asked about the differences between WebListener and [System.Net.HttpListener](https://msdn.microsoft.com/en-us/library/system.net.httplistener%28v=vs.110%29.aspx) .

Both components are C# HTTP servers built on top of Window's Http.Sys API. WebListener was originally forked from the HttpListener code, so they have a lot in common, but forking the code allowed us to make both functional and process related changes:
- Port the code to .NET Core
- Make breaking changes where required
- Ship independently on nuget.org
- Go open source
- Support new features on the existing .NET 4.5.1 framework

New features:
- SendFile - kernel mode optimization for static files
- Disconnect notifications
- Configure queue limit
- OPTIONS verb support

Other improvements:
- Real Task async APIs
- Performance optimizations, especially around request and response headers
- Removed the managed code implementation of Windows auth and used the Http.Sys kernel mode implementation instead. However, Digest auth was disabled.
- Updated the min OS to Win7 and removed XP specific code paths

**Comment by NimaAra** [comment]
Thanks for details above, so just to make it more clear for me, I was under the impression that _WebListener_ was/is Windows specific but then as you mentioned above, if ported to _.NET Core_ then we will have 2 XPlat servers (_Kestrel_ & _WebListener_) correct? With _Kestrel_ being ridiculously fast and _WebListener_ more reliable/secure due to _HttpSys_ and all.

**Comment by davidfowl** [comment]
> Thanks for details above, so just to make it more clear for me, I was under the impression that WebListener was/is Windows specific but then as you mentioned above, if ported to .NET Core then we will have 2 XPlat servers (Kestrel & WebListener) correct?

WebListener *is* and will always be windows specific.

**Comment by NimaAra** [comment]
@davidfowl Understood, tnx :-)

**Comment by darrelmiller** [comment]
Are you aware of any changes in WebListener over HttpListener that would improve the performance of doing the TLS handshake?

**Comment by davidfowl** [comment]
They are both using the same underlying API, SChannel https://msdn.microsoft.com/en-us/library/windows/desktop/aa380123(v=vs.85).aspx via http.sys so no

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
