### ISSUE TITLE
Many tests hang on VMs with only one core

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#275]
Most of the tests in Microsoft.AspNetCore.Server.WebListener.FunctionalTests are multi-threaded, but some of them have some poor threading practices, like calling Task.Result. See Server_AppException_ClientReset for a bad example.

The CI agents have multiple cores, but the machines we set up for local dev and debugging don't always.

**Comment by JunTaoLuo** [comment]
Spoke to @muratg Punting to preview2
