### ISSUE TITLE
Getting 401 Unauthorized when using Kerberos

### ISSUE THREAD

**Issue by ivan-prodanov** [aspnet/HttpSysServer#280]
I have a valid SPN set for the environment I'm testing this on and for the user that I run the application with, Negotiate works just fine (without falling back to NTLM) using WebListener. I can use just Negotiate:Kerberos as a provider in IIS and it works when the application is configured to use Kestrel. However if I try to use AuthenticationSchemes.Kerberos like below I get response 401 with absolutely no log shown in the WebListener console.

```
var host = new WebHostBuilder()
  .UseUrls("http://dev-001.devlab.local") // this PC.
  .UseWebListener(o => o.Listener.AuthenticationManager.AuthenticationSchemes = AuthenticationSchemes.Kerberos)
```

Is this a bug or I have done something wrong? I'm using a plain ASP.NET template application with the WebListener package and the aforementioned changes to Program.cs.

**Comment by Tratcher** [comment]
Side note: you appear to be using a pre-1.0 package, the APIs have changed slightly.
https://github.com/aspnet/WebListener/blob/dev/samples/SelfHostServer/Startup.cs#L20-L24

Does it work for you in IIS if you enable the kernel mode option? That's what WebListener uses.

**Comment by ivan-prodanov** [comment]
Indeed I was. Still same issues though. Here's the updated code:

```
                .UseUrls("http://*/Test")
                .UseWebListener(o =>
                {
                    o.EnableResponseCaching = false;
                    o.ListenerSettings.Authentication.AllowAnonymous = false;
                    o.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.Negotiate | AuthenticationSchemes.Kerberos;
                })
```

See the _Negotiate | Kerberos_ thing? This _seems_ fix it - negotiates only with Kerberos. However... I see that WebListener and Kestrel & IIS act in very different way in terms of authentication. I have much more serious 401 issue right now.

Using the following topology
Domain A:
  Client A
  Domain Account A

Domain B:
  Client B
  Domain Account B
  Server C
    <IIS Hosted App>
    <WebListener Hosted App>

A clean (file->new) application is hosted on one machine using:
  WebListener: http://*/Test by Domain Account A
  IIS&Kestrel: http://*/Test2 by Domain Account A

IIS is configured to use **only** Negotiate:Kerberos as an authentication provider without Kernel Mode authentication (extended protection is turned off though same result whether on/off or required). The application pool is runs by Domain Account A (the account that is associated to the SPN). 
WebListener is executed via "dotnet run <dll name>" by Domain Account A on the same machine.

Here's the **very weird** results
<WebListener Hosted App> 
From Client B using Domain Account B OK
From Client B using Domain Account A FAIL 401
From Client A using Domain Account B OK 
From Client A using Domain Account A FAIL 401

<IIS Hosted App>
From Client B using Domain Account B FAIL 401
From Client B using Domain Account A OK
From Client A using Domain Account B FAIL 401
From Client A using Domain Account A OK

How is it even possible for one to be the complete opposite of the other?!

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
