### ISSUE TITLE
[Announcement] WebListener packages and APIs merged and renamed

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#289]
The packages `Microsoft.AspNetCore.Server.WebListener` and `Microsoft.Net.Http.Server` have been merged into a new package `Microsoft.AspNetCore.Server.HttpSys`. The namespaces have been updated to match.

The WebHostBuilder extension has similarly been renamed from `UseWebListener` to `UseHttpSys`. The options for this extension have been flattened as shown [here](https://github.com/aspnet/MusicStore/commit/cd5a789b2b1ae6ad5fff04b5b518cbcb7314a6e6#diff-b423a04534faac96d57712aa2256aaf8L34).

The low level WebListener API has been removed to avoid duplication and confusion with HttpListener which has recently been added to .NET Core.

A few more consolidations and optimizations will follow, as discussed here: https://github.com/aspnet/WebListener/issues/283. The discussion issue will be updated accordingly with any additional breaking changes.

**Comment by scottaddie** [comment]
Will this repo be renamed to "HttpSys" as well?

**Comment by Tratcher** [comment]
Not right now. We'll continue to use WebListener as the project codename.

**Comment by davidfowl** [comment]
We should probably rename the repository as well /cc @Eilon

**Comment by Tratcher** [comment]
Just don't name it flat HttpSys, that would be too confusing. HttpSysIntegratoin like IISIntegration?

**Comment by Eilon** [comment]
Let me know and I'll rename it... GitHub will auto-redirect everything so it's quite safe.

**Comment by davidfowl** [comment]
> Just don't name it flat HttpSys, that would be too confusing. HttpSysIntegratoin like IISIntegration?

Why not? https://github.com/tjanczuk/httpsys 😄 

HttpSysIntegration is fine.

**Comment by Eilon** [comment]
Let's get confirmation from @DamianEdwards and I'll rename.

**Comment by Tratcher** [comment]
Is HttpSysServer any better? It mirrors KestrelHttpServer.

**Comment by davidfowl** [comment]
I like it better

**Comment by DamianEdwards** [comment]
HttpSysServer

**Comment by Eilon** [comment]
DONE.

**Comment by Tratcher** [comment]
One additional change: Direct WebSocket support has been removed from this new package. The application must now add the WebSocket middleware for WebSocket support. This mirrors the Kestrel architecture. There should not be any functional changes because the two components were previously sharing the same implementation code.

See https://github.com/aspnet/WebSockets/blob/b996ee39a429479e0bc301d198007cd85cc2acbd/samples/EchoApp/Startup.cs#L34 and the Microsoft.AspNetCore.WebSockets package.

**Comment by muratg** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
