### ISSUE TITLE
Malformed header causes infinite loop and never processes that request

### ISSUE THREAD

**Issue by tomhreb** [aspnet/HttpSysServer#299]
GET (for example) request with malformed header causes the process to go into infinite loop, causing high CPU usage and never gets into actually processing the request.

Example header: Accept:*/*Content-Type:application/json.

**Comment by tomhreb** [comment]
It's bug in Microsoft.AspNetCore.Mvc, not here.

**Comment by blowdart** [comment]
Linked to https://github.com/aspnet/Mvc/issues/5707
