### ISSUE TITLE
[1.1.1 patch] Don't wait indefinitely for requests to drain

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#301]
Backport to 1.1.1 @muratg 
https://github.com/aspnet/HttpSysServer/issues/298

**Comment by Eilon** [comment]
Re-opening because this not yet approved.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.
