### ISSUE TITLE
Gets tests working again on AppVeyor

### ISSUE THREAD

**Issue by dougbu** [aspnet/HttpSysServer#322]
Can't seem to find the old WebListener history on AppVeyor. But, as mentioned in PR #321, the recently-enabled tests using the correct name (https://ci.appveyor.com/project/aspnetci/httpsysserver/history) are not succeeding.

It appears all failures relate to IPv6 expectations i.e. the tests think IPv6 will definitely be enabled and the AppVeyor setup uses only IPv4. Suggest the failing tests should probably be differently-enabled where IPv6 is differently-enabled.

@muratg please reassign as appropriate.

**Comment by muratg** [comment]
@JunTaoLuo could you take a look?

**Comment by Eilon** [comment]
BTW I deleted and recreated the AppVeyor project for this repo because the rename of this repo was borking something. Hence, no history.

BTW if IPv6 is available for AppVeyor but we have to configure it, that could be a worthwhile avenue to investigate.

**Comment by JunTaoLuo** [comment]
Seems like tests are passing. Maybe https://github.com/aspnet/HttpSysServer/commit/bce80821c8b76a10882e5d2ad2a86ab05865ed75 fixed it?
