### ISSUE TITLE
[Patch 1.0.x] Leaking Windows Auth handles/memory

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#330]
https://github.com/aspnet/HttpSysServer/issues/317
https://github.com/aspnet/HttpSysServer/pull/329/commits/32bc9a57c94525326cd8c15c580db884c790d294

**Comment by muratg** [comment]
@Tratcher Could you file another one and put it in 1.1.2 milestone?

**Comment by Eilon** [comment]
This patch fix is *approved*. Please follow the normal code review / pull request process and make sure you make the change in the correct branch.

**Comment by Eilon** [comment]
Preview builds of this patch fix should be available on the following feeds:

* https://dotnet.myget.org/gallery/aspnet-1-0-5-may2017-patch-public (for fixes in the 1.0.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-0-5-may2017-patch-public/api/v3/index.json
* https://dotnet.myget.org/gallery/aspnet-1-1-2-may2017-patch-public (for fixes in the 1.1.x release)
  * Feed URL to add to NuGet.config: https://dotnet.myget.org/F/aspnet-1-1-2-may2017-patch-public/api/v3/index.json

If you have a chance, please try out these preview builds and let us know if you have any feedback!
