### ISSUE TITLE
[1.0.x patch] Fix API set target

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#348]
https://github.com/aspnet/HttpSysServer/pull/347
@jchannon

**Comment by muratg** [comment]
@Eilon Should we close this one (similar to #349)?

**Comment by Eilon** [comment]
Why close it?

**Comment by Tratcher** [comment]
It was rejected for the prior round of patches.

**Comment by Eilon** [comment]
If you guys don't want to fix a bug in a patch, that's fine with me. Just close it 😄

**Comment by muratg** [comment]
Closing this. The bug is fixed in 2.0.0 RTM, and we don't plan to bring the fix back to 1.x.
