### ISSUE TITLE
[1.1.x patch] Fix API set target

### ISSUE THREAD

**Issue by Tratcher** [aspnet/HttpSysServer#349]
https://github.com/aspnet/HttpSysServer/pull/347
@jchannon

**Comment by jchannon** [comment]
Excuse my lack of internal MS workflow but where do we go from this issue being marked as a "patch-proposed" to a patch?

**Comment by Eilon** [comment]
@jchannon this issue is not currently slated for a patch release. Would it be possible for you to use a custom build of the package? Or use a 2.0.0 nightly build (where this issue is already fixed).

**Comment by jchannon** [comment]
Would the custom build be built by myself? I could use a v2 nightly but I
assume that would mean upgrading our whole app to run on netcore v2?

**Comment by Eilon** [comment]
@jchannon yeah using 2.0 would mean using nightly 2.0 bits for the whole app. Would that work for you?

It should be pretty easy to make your own build: just clone the repo on Windows/Mac/Linux to the right branch/tag, make the change, and run `build` - it'll produce all the required NuGet packages and DLLs.

**Comment by muratg** [comment]
@Eilon should we close this one? (And #348)

**Comment by Eilon** [comment]
Why close it?

**Comment by muratg** [comment]
@Eilon IIRC, this was rejected for the previous patch release.

**Comment by Eilon** [comment]
Ok... if there are bugs we don't want to consider for the patch, go ahead and close 😄

**Comment by muratg** [comment]
Closing this. The bug is fixed in 2.0.0 RTM, and we don't plan to bring the fix back to 1.x.
