### ISSUE TITLE
Severe memory leak when using authentication

### ISSUE THREAD

**Issue by jcsharp** [aspnet/HttpSysServer#352]
I experience a severe memory leak when I use the WebListener v1.1.1 with Windows authentication enabled:

```C#
    var host = new WebHostBuilder()
        .UseWebListener(options =>
        {
            options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.Kerberos;
            options.ListenerSettings.Authentication.AllowAnonymous = false;
        })
        .UseStartup<Startup>()
        .Build();
```

With this configuration, a trivial web api leaks 12,600 bytes per request, which are not released until the service is restarted. 

If I remove the authentication requirement (`AllowAnonymous = true`), then the memory usage is stable.

I created a repository with code to reproduce this problem:
https://github.com/jcsharp/WebListenerLeak

**Comment by Tratcher** [comment]
Duplicate of https://github.com/aspnet/HttpSysServer/issues/317

**Comment by jcsharp** [comment]
Yes. I forgot to remove the `is:open` filter when I searched for `memory leak`...

I have verified that the v1.1.2 pre-release patch addresses my symptoms.
