### ISSUE TITLE
Explicity set path base for http.sys registration

### ISSUE THREAD

**Issue by DanielBryars** [aspnet/HttpSysServer#355]
I'm using version 1.1.1 (WebListener) and I want to explicitly set the "pathbase" used by the rest of the application routing instead of it being derived by the WebListener from the server url.

For example:
Process1
server.url = http://+:5000/
[Route("apigateway/api/v1/auth/")]
SomeController
[HttpGet("accounts/{accountId}/auth-token")
SomeMethod(int? accountId)

This will respond to a request such as expected:
http://localhost:5000/ApiGateway/api/v1/auth/accounts/1234/auth-token
client=>http.sys=>Process1=>routing=>mvc=>SomeController.SomeMethod

However, to enable my specific scenario, I want to register a more specific address with http.sys on an other instance of the process

For example:
Process2
server.url = http://+:5000/apigateway/api/v1/auth/accounts/7777/auth-token
[Route("apigateway/api/v1/auth/")]
SomeController
[HttpGet("accounts/{accountId}/auth-token")
SomeMethod(int? accountId)

This will still respond to a request such as expected in Process1:
http://localhost:5000/ApiGateway/api/v1/auth/accounts/1234/auth-token
client=>http.sys=>Process1=>routing=>mvc=>SomeController.SomeMethod

And http.sys will route the more specific URL to the second process as expected in the OS, but because the basepath or pathbase is now wrong in the application the mvc routing fails:

Ie this now routes to the second process, but routing fails:
http://localhost:5000/ApiGateway/api/v1/auth/accounts/7777/auth-token
client=>http.sys=>Process2=>routing=>mvc FAIL 404
because the request.pathbase = ApiGateway/api/v1/auth/accounts/7777/auth-token

The following does work:
http://localhost:5000/ApiGateway/api/v1/auth/accounts/7777/auth-token/ApiGateway/api/v1/auth/accounts/7777/auth-token
client=>http.sys=>Process2=>routing=>mvc=>SomeController.SomeMethod

I've looked at the source code and I don't understand how I can explicitly set this? I am open to plugging into the middleware layer and "manipulating" the base path my self, but I'm not sure exactly where to start. I did go down the path of making a IControllerModelConvention and messing with the routes in there, but it got messy fast and I struggled with the model parameters (ir the {accountId}) - I really need to set this base path at source in the IServer.

Please can you point me in the correct direction? Thanks.

**Comment by Tratcher** [comment]
Those are some very specific url registrations...

What you want is a middleware like https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UsePathBaseMiddleware.cs, but that operates in reverse, taking data from PathBase and moving it to Path.

**Comment by DanielBryars** [comment]
@Tratcher you legend; Thank you very much! I've written some Middleware to prepend the path with the pathbase.

And, indeed, yes the URL registrations are specific; my use case is perhaps a little odd, but very cool: I now have the ability to run a "general" instance of my service process which responds to all requests which are not handled by any other process which has registered a _more specific_ http.sys registration. In my scenario it allows me to have a different version of the process deployed for specific tenant, allowing a blastzone, security boundary, and independent versioning. It's opt in and "just works" :)
