### ISSUE TITLE
What happened to WebListener docs?

### ISSUE THREAD

**Issue by ferrx** [aspnet/HttpSysServer#358]
I'm reading the WebListener guide here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener and it frequently points to either portions of aspnet/HttpSysServer that no longer exist or it points to aspnet/WebListener which redirects to aspnet/HttpSysServer. (On further inspection it always points to aspnet/WebListener which redirects to HttpSysServer).

Does WebListener have a new name?

I'm just trying to read some documentation and it seems like it has been ripped from the universe. :( I want to know what the WebListenerOptions properties are, specifically if AllowAnonymous is true by default.. (assuming it's here now https://github.com/aspnet/HttpSysServer/blob/dev/src/Microsoft.AspNetCore.Server.HttpSys/AuthenticationManager.cs but really, looking through source code is no way to read documentation..)

**Comment by Tratcher** [comment]
Yes, WebListener was renamed to HttpSysServer for 2.0.

The docs aren't supposed to link to the dev branch... @tdykstra 

You can go back to the latest rel/1.1.2 branch to fix those links:
https://github.com/aspnet/HttpSysServer/blob/rel/1.1.2/src/Microsoft.AspNetCore.Server.WebListener/WebListenerOptions.cs
https://github.com/aspnet/HttpSysServer/blob/rel/1.1.2/src/Microsoft.Net.Http.Server/WebListenerSettings.cs

Are there any other broken links?

**Comment by ferrx** [comment]
Not seeing any other broken links. Thanks, I will take a look at that branch.

**Comment by tdykstra** [comment]
In Next steps we have 
https://github.com/aspnet/WebListener 
which isn't broken but not forwards to
https://github.com/aspnet/HttpSysServer

Since all of the links now have repo name HttpSysServer in them, maybe we should mention the upcoming name change somewhere in the doc.

**Comment by Tratcher** [comment]
We'll need to do a 2.0 doc update regardless. When are you doing 2.0 docs?

**Comment by tdykstra** [comment]
Probably more than 6 weeks from now.

**Comment by muratg** [comment]
Closing this bug as @tdykstra is tracking this on the docs side.
