### ISSUE TITLE
Add flag to disable synchronous IO

### ISSUE THREAD

**Issue by halter73** [aspnet/HttpSysServer#366]
This is the equivalent of https://github.com/aspnet/KestrelHttpServer/issues/1521.

Both servers will need to throw an InvalidOperationException on Request.Body.Read() and Response.Body.Write(). You can opt back in to synchronous IO using [IHttpBodyControlFeature.AllowSynchronousIO](https://github.com/aspnet/HttpAbstractions/blob/5472763fc27d3a84dc44eeef36c9ae1bf9bbdec6/src/Microsoft.AspNetCore.Http.Features/IHttpBodyControlFeature.cs#L14).

**Comment by Tratcher** [comment]
@muratg This needs to go into 2.0 or else it's a major breaking change.

**Comment by muratg** [comment]
Yeah, we decided to do this in Kestrel as well. Let's do it in 2.0.0.
