### ISSUE TITLE
SetRequestProcessingLimits support?

### ISSUE THREAD

**Issue by kadukf** [aspnet/HttpSysServer#382]
Is there a way to limit the max number of actual processing requests **w/o accepting new requests from the listener**? The similar thing what was implemented in Katana by calling "SetRequestProcessingLimits" ?

**Comment by Tratcher** [comment]
No, there is no matching setting.

**Comment by Tratcher** [comment]
@shirhatti at some point we're going to need to consider some form of back pressure here to keep from completely flooding the thread pool queue and memory.
