### ISSUE TITLE
Add IServiceProvider to HttpSysOptions

### ISSUE THREAD

**Issue by kdaveid** [aspnet/HttpSysServer#388]
In order to configure HttpSys with `WebHostBuilder` it would help to have access to `IServiceProvider` within `.UseHttpSys(Action<HttpSysOptions> options)` [extension method](https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0/src/Microsoft.AspNetCore.Server.Kestrel/WebHostBuilderKestrelExtensions.cs#L47). I.e. it would be nice to extract `IConfiguration` and use app settings from there.

This would be streamlined to Kestrel `KestrelServerOptions` https://github.com/aspnet/KestrelHttpServer/blob/rel/2.0.0/src/Microsoft.AspNetCore.Server.Kestrel.Core/KestrelServerOptions.cs#L51.

HttpSysOptions: https://github.com/aspnet/HttpSysServer/blob/rel/2.0.0/src/Microsoft.AspNetCore.Server.HttpSys/HttpSysOptions.cs

**Comment by Tratcher** [comment]
Note this has side effects. Kestrel's approach does not work with some DI containers because it relies on ordering. Capturing your dependencies via closure is more reliable.

**Comment by kdaveid** [comment]
Yes, I get that. I'm building a webapp that can be started in different ways (servers). I thought it's odd that the configuration are not the same. 

Feel free to close it.
