### ISSUE TITLE
[Test] Server_ClientDisconnects_CallCanceled sometimes takes much longer than average

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/HttpSysServer#391]
Sometimes [this](http://aspnetci/viewLog.html?buildId=312301&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win7_Universe#testNameId-5004057257646002980) test takes much longer than normal. Currently this was remedied by increasing the timeout, but we should investigate for possible performance improvements.

**Comment by muratg** [comment]
@ryanbrandenburg do you still see this? Noticed that this is not in your infrastructure project.

**Comment by ryanbrandenburg** [comment]
No more evidence of it, they seem to consistently take 20~ ms, I'm closing it.

Also, thanks for keeping an eye out for items I missed!
