### ISSUE TITLE
Hosting in http.sys does not allow both anonymous and Windows authentication to coexist

### ISSUE THREAD

**Issue by artisticcheese** [aspnet/HttpSysServer#394]
Code below does not work in http.sys while working in IIS where both anonymous and Windows authentication is specified and access to individual methods are based of tags

```
namespace Plain.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [Authorize]
        public IActionResult Windows()
        {
            return Content ("You are " + User.Identity.Name +  "; Authentication Type:" + User.Identity.AuthenticationType );
        }

        [AllowAnonymous]
        public IActionResult Anonymous()
        {
            return Content ("You are " + User.Identity.Name +  "; Authentication Type:" + User.Identity.AuthenticationType );;
        }
    }
    
}
```
```
 options.Authentication.Schemes =  AuthenticationSchemes.Negotiate | AuthenticationSchemes.NTLM;
            options.Authentication.AllowAnonymous = true;
```

**Comment by artisticcheese** [comment]
Documentation needs to be updated that services section shall contain following statement to allow both anonymous and Windows to work together

```
services.AddAuthentication(Microsoft.AspNetCore.Server.IISIntegration.IISDefaults.AuthenticationScheme);

```

**Comment by Tratcher** [comment]
Note HttpSys has it's own constant for this, `HttpSysDefaults.AuthenticationScheme` though the value happens to the be same as the one from IISDefaults uses.

**Comment by artisticcheese** [comment]
@Tratcher So I need to do 
`services.AddAuthentication(Microsoft.AspNetCore.Server.HttpSysDefaults.AuthenticationScheme);`?

**Comment by Tratcher** [comment]
Yes, otherwise `[Authorize]` will give you an error about no default scheme set.
