### ISSUE TITLE
Conditional authentication in Http.Sys

### ISSUE THREAD

**Issue by bencyoung** [aspnet/HttpSysServer#395]
In our previous OWIN app we used code like:

```csharp
            var listener = (HttpListener)appBuilder.Properties[typeof(HttpListener).FullName];
            listener.AuthenticationSchemeSelectorDelegate += httpRequest => AuthenticationSchemeSelectorDelegate(httpRequest, scheme);

        private static AuthenticationSchemes AuthenticationSchemeSelectorDelegate(
            HttpListenerRequest httpRequest,
            AuthenticationSchemes scheme)
        {
            if (string.Equals(httpRequest.Url.AbsolutePath, "/ping"))
            {
                return AuthenticationSchemes.Anonymous;
            }

            return httpRequest.Headers.Get("Access-Control-Request-Method") != null
                       ? AuthenticationSchemes.Anonymous
                       : scheme;
        }
```
to conditionally disable authentication requirements for certain paths and request types. Are we able to do something similar for Http.Sys and ASP.NET Core? I don't see the options when calling UseHttpSys:

```csharp
                .UseHttpSys(options =>
                {
                    options.Authentication.Schemes = AuthenticationSchemes.NTLM;
                    options.Authentication.AllowAnonymous = false;
                })
```

**Comment by davidfowl** [comment]
Why not do this further up the the stack? That is, issue the right challenge based on the resource being authenticated? Is there a reason you need to select schemes per request?

**Comment by bencyoung** [comment]
Hi David, how do I do that? Do you mean use a different WebHostBuilder for different request types? Or can I change the authentication scheme for different routes in MVC?

I guess one example shows above, where we need to allow anonymous access to the "ping" healthcheck endpoints so our monitoring software can access (uses a token instead for that)

Also we had issues when we applied required authentication for requests that had the Access-Control-Request-Method header as this was how certain browsers found out about the required authentication in the first place...

**Comment by davidfowl** [comment]
> Hi David, how do I do that? 

Depends on what you're trying to achieve. The basics of the auth system are here https://digitalmccullough.com/posts/aspnetcore-auth-system-demystified.html.

> Do you mean use a different WebHostBuilder for different request types? 

Nope.

> Or can I change the authentication scheme for different routes in MVC?

Yes. The authorize attribute lets you select a scheme.

> I guess one example shows above, where we need to allow anonymous access to the "ping" healthcheck endpoints so our monitoring software can access (uses a token instead for that)

That just means you need to allow anonymous for that end point.

> Also we had issues when we applied required authentication for requests that had the Access-Control-Request-Method header as this was how certain browsers found out about the required authentication in the first place... (needed for CORS preflight queries)

Are you using MVC at all? I'm guessing the Cors filter handles that nicely (but I'm just guessing).

Naiively I'm thinking your app would look like:

Program.cs

```C#
.UseHttpSys(options =>
{
    options.Authentication.Schemes = AuthenticationSchemes.NTLM;
    options.Authentication.AllowAnonymous = false;
});
```

Startup.cs

Startup.ConfigureServices

```C#
// Add the http.sys server auth scheme as the default scheme
services.AddAuthentication(HttpSysDefaults.AuthenticationScheme);

// Tell MVC to require an authenticated user everywhere
services.AddMvc(options =>
{
    var policy = new AuthorizationPolicyBuilder()
                    .RequireAuthenticatedUser()
                    .Build();
    options.Filters.Add(new AuthorizeFilter(policy));
});
```

Startup.Configure

```C#

app.UseAuthentication();

app.UseMvc();
```

Your application

```C#
public class MyController : Controller
{
   [AllowAnonymous]
   [HttpGet("/ping")]
   public Task Ping()
   {
        // some logic here
   }
}
```

**Comment by bencyoung** [comment]
Thanks, I'll give that a go. We're not using MVC for everything (some custom mapping, some MVC, some Nancy, some OWIN), so I suspect I'll need to look into exactly what AllowAnonymous and AuthorizationPolicyBuilder does at a low level

**Comment by davidfowl** [comment]
@bencyoung then read the blog post. It describes the low level mechanics of the system. Nancy doesn't integrate with the auth system, but there are services you can use to interact with it

**Comment by bencyoung** [comment]
@davidfowl. will do, once I get home and can see it where it's not blocked by my companies "helpful" corporate filter!

**Comment by davidfowl** [comment]
@bencyoung nice! The main difference between this and nancy will be how you require auth in nancy. That isn't very integrated with the ASP.NET Core authentication stack 

/cc @khellang @thecodejunkie

**Comment by muratg** [comment]
👍
