### ISSUE TITLE
Hosting Http.Sys in production environment

### ISSUE THREAD

**Issue by Eilon** [aspnet/HttpSysServer#404]
_From @rahulsahay19 on October 15, 2017 12:33_

Hi Team,

Wanted to understand one thing. Let's say, I have written ASP.NET Core MVC application which is hosted on Http.Sys. Therefore, currently what I do, I navigate to published folder and there run **dotnet app.dll**. Server gets started and it starts to listen requests. However, this also opened dotnet console window, which is ok if I am doing development on local machine.

But, let's say I would like to take the published folder and deploy on server. Therefore, if I run the same command **dotnet app.dll**, server will get launched and start listening as well, I believe. But, it will have the same console window remain opened there. Is there any way to start the server as a background process, I mean server should keep running but cmd prompt shouldn't be there.

Thanks,
Rahul

_Copied from original issue: aspnet/Mvc#6958_

**Comment by Eilon** [comment]
(This isn't really an HttpSysServer issue either, but moved it here anyway because that's what the question is about.)

**Comment by Eilon** [comment]
@rahulsahay19 it's up to you how you want to launch the app. You can run it via a Windows Service, or any other mechanism. There shouldn't be any problem with having an extra command window open. Presumably no one remains logged into the server so having an extra window open there shouldn't be a problem. But, running as a Windows Service is better from a user-isolation perspective and avoiding launching server processes in an interactive session.

cc @glennc in case you have more thoughts on this.

**Comment by rahulsahay19** [comment]
Hmm. Thanks for the reply.
