### ISSUE TITLE
[Patch 2.0.x] ArgumentNullException("chars") is thrown when iterating HeaderDictionary

### ISSUE THREAD

**Issue by muratg** [aspnet/HttpSysServer#410]
Original issue is [here](https://github.com/aspnet/HttpSysServer/issues/381) and is fixed.

We'd like to propose this for a patch release.

**Comment by muratg** [comment]
cc @Eilon @Tratcher @mikeharder 

This is a candidate for 2.0.2.

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.

**Comment by Tratcher** [comment]
@Eilon I'm not planning to add a quirk flag for this behavior. The error is very disruptive and the fix is very low risk. See the linked PR.

**Comment by Eilon** [comment]
@Tratcher yeah I think that's reasonable here. Thanks for considering it.
