### ISSUE TITLE
Hosting API with windows auth both as selfhosted HTTP.sys and in IIS?

### ISSUE THREAD

**Issue by codepunkt** [aspnet/HttpSysServer#425]
I'm building a service based on dotnet core 2.0 that should run both as a self-hosted console application and hosted in IIS. The service runs in a windows environment and must support windows auth.

Early on, i used kestrel with `UseKestrel()`, but then found out that kestrel doesn't support windows auth and i should use HTTP.sys - so i switched to this startup code:

```c#
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseHttpSys(options =>
            {
                options.Authentication.Schemes = AuthenticationSchemes.NTLM |
                    AuthenticationSchemes.Negotiate;
                options.Authentication.AllowAnonymous = false;
                options.MaxConnections = 100;
                options.MaxRequestBodySize = 30000000;
                options.UrlPrefixes.Add("http://localhost:5000");
            })
        .UseIISIntegration()
        .UseStartup<Startup>()
        .Build();
```

When publishing this with `dotnet publish -c Release -r win10-x64` and using the resulting release in IIS, i get `HTTP Error 502.5 - Process Failure` for all URLs. I couldn't find solid information on why this happened - but i found that the HTTP.sys server won't work in a reverse proxy configuration with IIS so i removed the `.UseHttpSys()` setup and voila - hosting in IIS works.

Now i'm left a little baffled. How do i write an API that supports windows auth and can be hosted both as standalone console app and in IIS? Is this the right direction and there is a way to detect if running in IIS or not so i can `.UseHttpSys()` only when needed?

Any help is very appreciated!

**Comment by Tratcher** [comment]
Unfortunately you must use config or command line parameters to select Kestrel vs HttpSys in BuildWebHost. There's a slightly complex example here: https://github.com/aspnet/MusicStore/blob/5086579c4259ba6e8a7ff9d7edd808d62f2396e4/samples/MusicStore/Program.cs#L31

**Comment by Tratcher** [comment]
Triage note: This will no longer be an issue with the new IIS in-proc support, as Kestrel will no longer be required.

**Comment by davidfowl** [comment]
This is how the UseIISIntegration method detect's if it's being hosted in reverse proxy mode:

https://github.com/aspnet/IISIntegration/blob/6f54ed1c68ad732802b8813dad4c6f0b872d8c0b/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L73-L78

You can actually take advantage of this in your own extension method to do the dynamic light up depending on where you're running. the IIS Integration method sets a flag:

https://github.com/aspnet/IISIntegration/blob/df88e322cc5e52db3dbce4060d5bc7db88edb8e4/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L50

That you can use to determine if it's "effective". Here's an example:

```C#
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseHttpSysOrIISIntegration()
                .UseStartup<Startup>()
                .Build();
    }

    public static class WebHostBuilderExtensions
    {
        public static IWebHostBuilder UseHttpSysOrIISIntegration(this IWebHostBuilder builder)
        {
            if (builder.GetSetting("UseIISIntegration") == null)
            {
                // Self hosted
                builder.UseHttpSys(options =>
                {
                    options.Authentication.Schemes = AuthenticationSchemes.NTLM |
                        AuthenticationSchemes.Negotiate;
                    options.Authentication.AllowAnonymous = false;
                    options.MaxConnections = 100;
                    options.MaxRequestBodySize = 30000000;
                    options.UrlPrefixes.Add("http://localhost:5000");
                });
            }

            return builder;
        }
    }
```


PS: Thee's no need to call UseIISIntegration, CreateDefaultBuilder already does this.

**Comment by codepunkt** [comment]
@davidfowl

**Comment by codepunkt** [comment]
Thanks for both of your time and effort. Your dedication really make a difference for dotnet newcomers like myself! 😄 

@davidfowl 
I removed the `UseIISIntegration` and implemented the WebHostBuilderExtension like shown. Works like a charm! To really understand what's going on here, i've got a few additional questions:
- Why do the settings `port`, `path` and `pairingToken` tell us that we're hosted in IIS?
- Where are they actually read from when being hosted in IIS - IWebHostBuilder settings or ASPNETCORE_* env vars?
- What would happen if i would set the corresponding ASPNETCORE_* env vars while running in selfhosted mode?
- Is there a documentation about the available ASPNETCORE_* env vars somewhere?

@Tratcher 
That example does a lot of things during initialization that i can't get my head around - yet. Thanks for the input, this will keep me busy a few hours. The `MusicStore` app does lots of different things initialization-wise when compared to a simple `CreateDefaultBuilder`.
Is there a step by step guide for everything that can be achieved using IWebHostBuilder or the steps taken in `CreateDefaultBuilder` and why they are (most likely) sane defaults?

**Comment by davidfowl** [comment]
> Why do the settings port, path and pairingToken tell us that we're hosted in IIS?

Those are the environment variables that the ASP.NET Core module sets when to boots the dotnet process.

> Where are they actually read from when being hosted in IIS - IWebHostBuilder settings or ASPNETCORE_* env vars?

Hosting reads all ASPNETCORE_ environment variables and adds them to configuration by default. (https://github.com/aspnet/Hosting/blob/cb55973c27ca4bf2333c509edadab62c909e3c52/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L46)

We fallback to reading environment variables directly in case the builder is customized t not do this (which is pretty rare).

> What would happen if i would set the corresponding ASPNETCORE_* env vars while running in selfhosted mode?

It would activate the IIS Integration component and then likely fail at runtime when things don't line up (like the pairing token).

> Is there a documentation about the available ASPNETCORE_* env vars somewhere?

The main ones, these env variables are a contract between the IIS module and IIS Integration.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
