### ISSUE TITLE
Flaky test: Caching_InvalidExpires_NotCached

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/HttpSysServer#441]
This test [fails occasionally](http://aspnetci/viewLog.html?buildId=439056&buildTypeId=XPlat_Windows_Win2008r2_Universe), seemingly specific to 2008.

```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.SendRequestAsync(String uri) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\HttpSysServer\test\Microsoft.AspNetCore.Server.HttpSys.FunctionalTests\ResponseCachingTests.cs:line 217
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_InvalidExpires_NotCached(String expiresValue) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\HttpSysServer\test\Microsoft.AspNetCore.Server.HttpSys.FunctionalTests\ResponseCachingTests.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
```

Future instances of this failure will appear [here](http://aspnetci/project.html?projectId=XPlat&testNameId=2650392098769139334&tab=testDetails).

**Comment by ryanbrandenburg** [comment]
This test appears to be [skipped XPlat](http://aspnetci/project.html?tab=testDetails&testNameId=2650392098769139334&projectId=Releases_21Public&buildTypeId=Releases_21Public_UbuntuUniverse&order=TEST_STATUS_DESC) though it's unclear to me through what method.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/HttpSysServer/blob/adbbbcf4deed896f8a828c46ea5ff932b532dd57/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/Properties/AssemblyInfo.cs#L7-L8

**Comment by ryanbrandenburg** [comment]
Caching_InvalidExpires_NotCached [failed again](http://aspnetci/viewLog.html?buildId=516857&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Caching_InvalidExpires_NotCached [failed again](http://aspnetci/viewLog.html?buildId=518638&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Caching_InvalidExpires_NotCached [failed with about the same error](http://aspnetci/viewLog.html?buildId=526220&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Caching_InvalidExpires_NotCached [failed with about the same error](http://aspnetci/viewLog.html?buildId=529940&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AuthTypes_AllowAnonymous_NoChallenge [failed with about the same error](http://aspnetci/viewLog.html?buildId=532004&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AuthTypes_AllowAnonymous_NoChallenge [failed with about the same error](http://aspnetci/viewLog.html?buildId=534660&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Caching_InvalidExpires_NotCached [failed with about the same error](http://aspnetci/viewLog.html?buildId=535659&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=583734&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:52:06 AM:
- RequestBody_ReadAsyncPartialBodyAndExpiredTimeout_Canceled

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=589479&buildTypeId=XPlat_Windows_Win7_Universe) on master at 8:53:27 AM:
- Caching_InvalidExpires_NotCached
