### ISSUE TITLE
UseHttpSys against IServiceCollection to support generic host

### ISSUE THREAD

**Issue by chuanboz** [aspnet/HttpSysServer#448]
see https://github.com/aspnet/KestrelHttpServer/issues/2498 for Kestrel.

similar issue exists for UseHttpSys, and it's even harder as MessagePump class is marked as internal.

'
public static IServiceCollection UseHttpSys(this IServiceCollection services)
        {
            services.AddSingleton<IServer, MessagePump>();
            services.AddAuthenticationCore();
            return services;
        }
'

**Comment by muratg** [comment]
Design around this has changed. We don't need this anymore.

**Comment by chuanboz** [comment]
thanks @muratg , do you have a link to the changed design around this? just trying to understand the latest design better.

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Hosting/pull/1580
