### ISSUE TITLE
Flaky test: ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/HttpSysServer#451]
This test [fails](http://aspnetci/viewLog.html?buildId=457138&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.HttpSys.Listener.ResponseBodyTests.<SendRequestAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment]
ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts [failed again](http://aspnetci/viewLog.html?buildId=517546&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts [failed with about the same error](http://aspnetci/viewLog.html?buildId=520543&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ResponseBody_WriteContentLengthTooMuchWritten_Throws [failed with about the same error](http://aspnetci/viewLog.html?buildId=530433&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ResponseBody_WriteContentLengthNotEnoughWritten_Aborts [failed with about the same error](http://aspnetci/viewLog.html?buildId=540941&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ResponseBody_WriteContentLengthTooMuchWritten_Throws [failed with about the same error](http://aspnetci/viewLog.html?buildId=541635&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts [failed with about the same error](http://aspnetci/viewLog.html?buildId=544644&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AuthTypes_AllowAnonymous_NoChallenge [failed with about the same error](http://aspnetci/viewLog.html?buildId=548632&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts [failed with about the same error](http://aspnetci/viewLog.html?buildId=550008&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AuthTypes_AllowAnonymous_NoChallenge [failed with about the same error](http://aspnetci/viewLog.html?buildId=551028&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Caching_InvalidExpires_NotCached [failed with about the same error](http://aspnetci/viewLog.html?buildId=554724&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AuthTypes_AllowAnonymous_NoChallenge [failed with about the same error](http://aspnetci/viewLog.html?buildId=556169&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ResponseBody_WriteContentLengthNotEnoughWritten_Aborts [failed with about the same error](http://aspnetci/viewLog.html?buildId=556969&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Caching_InvalidExpires_NotCached [failed with about the same error](http://aspnetci/viewLog.html?buildId=558369&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=560221&buildTypeId=XPlat_Windows_Win7_Universe) on master:
- ResponseBody_WriteContentLengthNotEnoughWritten_Aborts


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=564327&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master:
- Caching_InvalidExpires_NotCached


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=567000&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 3:17:24 PM:
- ResponseBodyWriteExceptions_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=571066&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 7:48:32 PM:
- AuthTypes_AllowAnonymous_NoChallenge

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=572238&buildTypeId=XPlat_Windows_Win7_Universe) on master at 1:47:34 PM:
- Caching_InvalidExpires_NotCached

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=572388&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 8:24:44 PM:
- ResponseBody_WriteContentLengthTooMuchWritten_Throws

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=578536&buildTypeId=XPlat_Windows_Win7_Universe) on master at 8:14:37 PM:
- AuthTypes_AllowAnonymous_NoChallenge

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=580401&buildTypeId=Lite_UniverseTest) on master at 8:37:02 PM:
- ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts

**Comment by Tratcher** [comment]
ResponseBody_SecondWriteAsyncWithCanceledCancellationToken_CancelsAndAborts
2 failures
- [10643](http://aspnetci/viewLog.html?buildId=580401&buildTypeId=Lite_UniverseTest&tab=buildResultsDiv) Win 2012, .NET 4.6.1 only.
- [10557](http://aspnetci/viewLog.html?buildId=567765&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win2008r2_Universe#testNameId-1955952822284369934), 2008 R2, net461

Note this is a Listener style test that should be re-written.

**Comment by Tratcher** [comment]
Everything above has been resolved except Caching_InvalidExpires_NotCached and the issue described in the prior post.

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=581332&buildTypeId=XPlat_Windows_Win7_Universe) on master at 1:59:59 AM:
- RequestBody_ReadAsyncPartialBodyAndExpiredTimeout_Canceled

**Comment by Tratcher** [comment]
Closing this out. Fixes or mitigations have been added for all failures.
