### ISSUE TITLE
Test failure: AuthTypes_UnathorizedAuthenticatedAuthType_Unauthorized

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/HttpSysServer#474]
This test [fails](http://aspnetci/viewLog.html?buildId=543953&buildTypeId=Releases_22xPublic_Win2012) occasionally with the following error:
```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'System.Net.Http.HttpConnection+HttpConnectionResponseContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.HttpSys.AuthenticationTests.SendRequestAsync(String uri, Boolean useDefaultCredentials) in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs:line 377
   at Microsoft.AspNetCore.Server.HttpSys.AuthenticationTests.AuthTypes_UnathorizedAuthenticatedAuthType_Unauthorized(AuthenticationSchemes authType) in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs:line 364
--- End of stack trace from previous location where exception was thrown ---
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @Eilon (because the bot doesn't know who else to pick)

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AuthTypes_UnathorizedAuthenticatedAuthType_Unauthorized [failed with about the same error](http://aspnetci/viewLog.html?buildId=544163&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AuthTypes_UnathorizedAuthenticatedAuthType_Unauthorized [failed with about the same error](http://aspnetci/viewLog.html?buildId=544644&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Eilon** [comment]
@muratg please assign.

**Comment by Tratcher** [comment]
3 failures, all in 2.2.

It doesn't seem to be timing out, the test only runs for ~1s.

HttpClient regression? @davidsh
```
Object name: 'System.Net.Http.HttpConnection+HttpConnectionResponseContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.HttpSys.AuthenticationTests.SendRequestAsync(String uri, Boolean useDefaultCredentials) in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs:line 377
```
Related? https://github.com/dotnet/corefx/pull/31589

The calling code isn't doing anything interesting.
https://github.com/aspnet/HttpSysServer/blob/9cb675fec89702d28b5f188e0ab4f7d671d7aa11/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/AuthenticationTests.cs#L371-L379

**Comment by Eilon** [comment]
@Tratcher if you suspect something in CoreFX, please also send mail so we can get it into their inboxes faster.

**Comment by aspnet-hello** [comment]
AuthTypes_UnathorizedAuthenticatedAuthType_Unauthorized [failed with about the same error](http://aspnetci/viewLog.html?buildId=544971&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by Tratcher** [comment]
Filed https://github.com/dotnet/corefx/issues/32143.

This does not repro in 2.2 when I run the test manually, but in 3.0 it does fail even for manual runs.

**Comment by Tratcher** [comment]
I was able to reproduce this in the release/2.2 branch after I did `run upgrade deps`.

This is now skipped in release/2.2 and master.

Corefx has found the issue and submitted a PR.

**Comment by aspnet-hello** [comment]
AuthTypes_UnathorizedAuthenticatedAuthType_Unauthorized [failed with about the same error](http://aspnetci/viewLog.html?buildId=546427&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
