### ISSUE TITLE
Test failure: UseDefaultAddress_WhenNoServerAddressAndNoDirectConfiguration

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/HttpSysServer#482]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=580577&buildTypeId=Releases_22xPublic_Win2012) with the following error:

```
Microsoft.AspNetCore.Server.HttpSys.HttpSysException : The process cannot access the file because it is being used by another process
   at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId) in /_/src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/UrlGroup.cs:line 90
   at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup) in /_/src/Microsoft.AspNetCore.Server.HttpSys/UrlPrefixCollection.cs:line 141
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start() in /_/src/Microsoft.AspNetCore.Server.HttpSys/HttpSysListener.cs:line 157
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Server.HttpSys/MessagePump.cs:line 132
   at Microsoft.AspNetCore.Server.HttpSys.MessagePumpTests.UseDefaultAddress_WhenNoServerAddressAndNoDirectConfiguration() in /_/test/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests/MessagePumpTests.cs:line 115
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC Eilon

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=580423&buildTypeId=Releases_22xPublic_Win2012) on 2.2 at 10:13:55 PM:
- UseDefaultAddress_WhenNoServerAddressAndNoDirectConfiguration

**Comment by Eilon** [comment]
@Tratcher can you take a look?

**Comment by Tratcher** [comment]
I blame [SignalR](https://github.com/aspnet/SignalR/issues/3161). @BrennanConroy why are those tests all using 5000?

**Comment by Eilon** [comment]
So assign this to @BrennanConroy 5000 times? 😄
